//var TERMS = ['accessibility', 'agile', 'ajax', 'apache', 'api', 'angular', 'aws', 'backbone', 'bem', 'bootstrap', 'browserify', 'cassandra', 'chai', 'codeignitor', 'command line', 'css', 'django', 'docker', 'ember', 'foundation', 'git', 'github', 'grunt', 'gulp', 'hbase', 'html', 'jasmine', 'javascript', 'jenkins', 'jekyll', 'jest', 'jira', 'jquery', 'json', 'karma', 'kohona', 'less', 'linux', 'marionette', 'mobile', 'mocha', 'mongo', 'nginx', 'mvc', 'node', 'npm', 'nosql', 'open source', 'oocss', 'perl', 'photoshop', 'php', 'postcss', 'protractor', 'puppet', 'python', 'rails', 'react', 'redux', 'restful', 'ruby', 'sass', 'sinon', 'sql', 'symfony', 'tomcat', 'ui', 'vagrant', 'vue', 'webpack', 'wireframes', 'wordpress', 'zend'];
var counter = {
    'date' : new Date(),
    'front-end': [
        { 'name': 'accessibility', 'value': 0 },
        { 'name': 'agile', 'value': 0 },
        { 'name': 'ajax', 'value': 0 },
        { 'name': 'apache', 'value': 0 },
        { 'name': 'api', 'value': 0 },
        { 'name': 'angular', 'value': 0 },
        { 'name': 'asp', 'value': 0 },
        { 'name': 'aws', 'value': 0 },
        { 'name': 'backbone', 'value': 0 },
        { 'name': 'bem', 'value': 0 },
        { 'name': 'bootstrap', 'value': 0 },
        { 'name': 'browserify', 'value': 0 },
        { 'name': 'c#', 'value': 0 },
        { 'name': 'c++', 'value': 0 },
        { 'name': 'cassandra', 'value': 0 },
        { 'name': 'chai', 'value': 0 },
        { 'name': 'codeignitor', 'value': 0 },
        { 'name': 'command line', 'value': 0 },
        { 'name': 'd3', 'value': 0 },
        { 'name': 'django', 'value': 0 },
        { 'name': 'docker', 'value': 0 },
        { 'name': 'ecma', 'value': 0 },
        { 'name': 'ember', 'value': 0 },
        { 'name': 'express', 'value': 0 },
        { 'name': 'foundation', 'value': 0 },
        { 'name': 'git', 'value': 0 },
        { 'name': 'github', 'value': 0 },
        { 'name': 'grunt', 'value': 0 },
        { 'name': 'gulp', 'value': 0 },
        { 'name': 'hbase', 'value': 0 },
        { 'name': 'jasmine', 'value': 0 },
        { 'name': 'jekyll', 'value': 0 },
        { 'name': 'jenkins', 'value': 0 },
        { 'name': 'jest', 'value': 0 },
        { 'name': 'jira', 'value': 0 },
        { 'name': 'jquery', 'value': 0 },
        { 'name': 'json', 'value': 0 },
        { 'name': 'karma', 'value': 0 },
        { 'name': 'kohana', 'value': 0 },
        { 'name': 'less', 'value': 0 },
        { 'name': 'linux', 'value': 0 },
        { 'name': 'marionette', 'value': 0 },
        { 'name': 'mobile', 'value': 0 },
        { 'name': 'mocha', 'value': 0 },
        { 'name': 'mongo', 'value': 0 },
        { 'name': 'mvc', 'value': 0 },
        { 'name': '.net', 'value': 0 },
        { 'name': 'nginx', 'value': 0 },
        { 'name': 'node', 'value': 0 },
        { 'name': 'nosql', 'value': 0 },
        { 'name': 'npm', 'value': 0 },
        { 'name': 'oocss', 'value': 0 },
        { 'name': 'open source', 'value': 0 },
        { 'name': 'photoshop', 'value': 0 },
        { 'name': 'php', 'value': 0 },
        { 'name': 'perl', 'value': 0 },
        { 'name': 'polymer', 'value': 0 },
        { 'name': 'postcss', 'value': 0 },
        { 'name': 'protractor', 'value': 0 },
        { 'name': 'puppet', 'value': 0 },
        { 'name': 'python', 'value': 0 },
        { 'name': 'rails', 'value': 0 },
        { 'name': 'react', 'value': 0 },
        { 'name': 'redux', 'value': 0 },
        { 'name': 'restful', 'value': 0 },
        { 'name': 'ruby', 'value': 0 },
        { 'name': 'sass', 'value': 0 },
        { 'name': 'saas', 'value': 0 },
        { 'name': 'sinon', 'value': 0 },
        { 'name': 'symfony', 'value': 0 },
        { 'name': 'sql', 'value': 0 },
        { 'name': 'tomcat', 'value': 0 },
        { 'name': 'ux', 'value': 0 },
        { 'name': 'vagrant', 'value': 0 },
        { 'name': 'vue', 'value': 0 },
        { 'name': 'webpack', 'value': 0 },
        { 'name': 'wireframes', 'value': 0 },
        { 'name': 'wordpress', 'value': 0 },
        { 'name': 'zend', 'value': 0 }
    ]
}

module.exports = counter;